### ISSUE TITLE
Odd behavior: Alternation fails instead of trying second alternative

### ISSUE THREAD

**Issue by theHacker** [ohmjs/ohm#489]
Hi. I am just exploring Ohm in the online editor.

When using this grammar:
```
Demo {

  // does not work as expected
  Query = EmptyQuery | NotEmptyQuery
  
  // works as expected
  // Query = NotEmptyQuery | EmptyQuery

  EmptyQuery = ""
  NotEmptyQuery = any+
}
```
I am confused to as why it makes a difference in which order I put the alternations.

With `Query = NotEmptyQuery | EmptyQuery`:
- the empty string will match the `EmptyQuery`
- any non-empty string will match the `NotEmptyQuery`

However, with  `Query = EmptyQuery | NotEmptyQuery `:
- the empty string will match as `EmptyQuery`
- any non-empty string will **fail** as `EmptyQuery` and `Expected end of input`.

Why?! The reference says about the Alternation

> Matches the expression `expr1`, and if that does not succeed, matches the expression `expr2`.

Should the parser not try the second alternative, i.e. `NotEmptyQuery`?

(When I alter the rule to `EmptyQuery = "" end`, it works as expected).

Is this a bug? Or am I misunderstanding something here?

**Comment by pdubroy** [comment]
Sorry for not responding earlier!

This is a common confusion, especially for people are used to the behaviour of regular expressions. In PEG parsers like Ohm, the `|` operator is an ordered choice that commits to the first successful match, even if it's partial.

In your example, `EmptyQuery` will always succeed and consume no input. That's why `NotEmptyQuery` is never tried in the "does not work as expected" case. The fact that this choice eventually leads to an overall failed parse does not factor into it.

There are pros and cons to both approaches. This behaviour of PEGs has the advantage that it maps in an very direct way to a hand-written, top-down parser.
